
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class view_cart extends javax.swing.JFrame {

    /**
     * Creates new form view_cart
     */
    ArrayList al=new ArrayList();
    public view_cart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        item_1 = new javax.swing.JLabel();
        item_2 = new javax.swing.JLabel();
        item_3 = new javax.swing.JLabel();
        item_4 = new javax.swing.JLabel();
        item_5 = new javax.swing.JLabel();
        item_6 = new javax.swing.JLabel();
        item_7 = new javax.swing.JLabel();
        item_8 = new javax.swing.JLabel();
        item_9 = new javax.swing.JLabel();
        item_10 = new javax.swing.JLabel();
        item_11 = new javax.swing.JLabel();
        item_12 = new javax.swing.JLabel();
        item_13 = new javax.swing.JLabel();
        item_14 = new javax.swing.JLabel();
        item_15 = new javax.swing.JLabel();
        item_16 = new javax.swing.JLabel();
        item_17 = new javax.swing.JLabel();
        item_18 = new javax.swing.JLabel();
        item_19 = new javax.swing.JLabel();
        item_20 = new javax.swing.JLabel();
        item_21 = new javax.swing.JLabel();
        item_22 = new javax.swing.JLabel();
        item_23 = new javax.swing.JLabel();
        item_24 = new javax.swing.JLabel();
        item_25 = new javax.swing.JLabel();
        item_26 = new javax.swing.JLabel();
        item_27 = new javax.swing.JLabel();
        item_28 = new javax.swing.JLabel();
        item_29 = new javax.swing.JLabel();
        item_30 = new javax.swing.JLabel();
        item_31 = new javax.swing.JLabel();
        item_32 = new javax.swing.JLabel();
        item_33 = new javax.swing.JLabel();
        item_34 = new javax.swing.JLabel();
        item_35 = new javax.swing.JLabel();
        item_36 = new javax.swing.JLabel();
        item_37 = new javax.swing.JLabel();
        item_38 = new javax.swing.JLabel();
        item_39 = new javax.swing.JLabel();
        item_40 = new javax.swing.JLabel();
        item_41 = new javax.swing.JLabel();
        item_42 = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\dessert icon.png")); // NOI18N
        jButton2.setText("Desserts");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, 80));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\fast-food.png")); // NOI18N
        jButton4.setText("Order Now");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 80));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\italian_icon.png")); // NOI18N
        jButton5.setText("Italian Food");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 80));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\home-icon-silhouette.png")); // NOI18N
        jButton6.setText("Home");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 80));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\laddu.png")); // NOI18N
        jButton7.setText("Indian Food");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 80));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\sousouth icon.png")); // NOI18N
        jButton8.setText("South Indian");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 80));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\chinese icon.png")); // NOI18N
        jButton9.setText("Chinese");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 80));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\drinks icon.png")); // NOI18N
        jButton10.setText("Drinks");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 250, 80));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\back.png")); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 250, 90));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\home-icon-silhouette.png")); // NOI18N
        jButton11.setText("Home");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 250, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\storage.png")); // NOI18N
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 250, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\rupee.png")); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 170, 180, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\fast-food.png")); // NOI18N
        jLabel4.setText("Items");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 180, 70));

        item_1.setText("jLabel5");
        item_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 280, 240, 30));

        item_2.setText("jLabel6");
        item_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 330, 240, 30));

        item_3.setText("jLabel7");
        item_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 380, 240, 30));

        item_4.setText("jLabel8");
        item_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 430, 240, 30));

        item_5.setText("jLabel9");
        item_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 480, 240, 30));

        item_6.setText("jLabel10");
        item_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 530, 240, 30));

        item_7.setText("jLabel11");
        item_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 580, 240, 30));

        item_8.setText("jLabel12");
        item_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 630, 240, 30));

        item_9.setText("jLabel13");
        item_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 680, 240, 30));

        item_10.setText("jLabel14");
        item_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 730, 240, 30));

        item_11.setText("jLabel15");
        item_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 780, 240, 30));

        item_12.setText("jLabel16");
        item_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 830, 240, 30));

        item_13.setText("jLabel17");
        item_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 880, 240, 30));

        item_14.setText("jLabel18");
        item_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 930, 240, 30));

        item_15.setText("jLabel5");
        item_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 240, 30));

        item_16.setText("jLabel6");
        item_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 240, 30));

        item_17.setText("jLabel7");
        item_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 240, 30));

        item_18.setText("jLabel8");
        item_18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 240, 30));

        item_19.setText("jLabel9");
        item_19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 240, 30));

        item_20.setText("jLabel10");
        item_20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 240, 30));

        item_21.setText("jLabel11");
        item_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 240, 30));

        item_22.setText("jLabel12");
        item_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 240, 30));

        item_23.setText("jLabel13");
        item_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 690, 240, 30));

        item_24.setText("jLabel14");
        item_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 740, 240, 30));

        item_25.setText("jLabel15");
        item_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 790, 240, 30));

        item_26.setText("jLabel16");
        item_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 840, 240, 30));

        item_27.setText("jLabel17");
        item_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 880, 240, 30));

        item_28.setText("jLabel18");
        item_28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 930, 240, 30));

        item_29.setText("jLabel5");
        item_29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_29, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 240, 30));

        item_30.setText("jLabel6");
        item_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_30, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 240, 30));

        item_31.setText("jLabel7");
        item_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_31, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 240, 30));

        item_32.setText("jLabel8");
        item_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_32, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 240, 30));

        item_33.setText("jLabel9");
        item_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_33, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 240, 30));

        item_34.setText("jLabel10");
        item_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_34, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 240, 30));

        item_35.setText("jLabel11");
        item_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, 240, 30));

        item_36.setText("jLabel12");
        item_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 240, 30));

        item_37.setText("jLabel13");
        item_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 240, 30));

        item_38.setText("jLabel14");
        item_38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_38, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 740, 240, 30));

        item_39.setText("jLabel15");
        item_39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_39, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 790, 240, 30));

        item_40.setText("jLabel16");
        item_40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_40, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 840, 240, 30));

        item_41.setText("jLabel17");
        item_41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_41, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 880, 240, 30));

        item_42.setText("jLabel18");
        item_42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(item_42, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 920, 240, 30));

        subtotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        subtotal.setText("Subtotal :-");
        jPanel1.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 740, 260, 50));

        rate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rate.setText("400");
        rate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 800, 180, 50));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Desktop\\Food Escort\\coin.png")); // NOI18N
        jButton1.setText("Pay Now");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 880, 260, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item_1;
    private javax.swing.JLabel item_10;
    private javax.swing.JLabel item_11;
    private javax.swing.JLabel item_12;
    private javax.swing.JLabel item_13;
    private javax.swing.JLabel item_14;
    private javax.swing.JLabel item_15;
    private javax.swing.JLabel item_16;
    private javax.swing.JLabel item_17;
    private javax.swing.JLabel item_18;
    private javax.swing.JLabel item_19;
    private javax.swing.JLabel item_2;
    private javax.swing.JLabel item_20;
    private javax.swing.JLabel item_21;
    private javax.swing.JLabel item_22;
    private javax.swing.JLabel item_23;
    private javax.swing.JLabel item_24;
    private javax.swing.JLabel item_25;
    private javax.swing.JLabel item_26;
    private javax.swing.JLabel item_27;
    private javax.swing.JLabel item_28;
    private javax.swing.JLabel item_29;
    private javax.swing.JLabel item_3;
    private javax.swing.JLabel item_30;
    private javax.swing.JLabel item_31;
    private javax.swing.JLabel item_32;
    private javax.swing.JLabel item_33;
    private javax.swing.JLabel item_34;
    private javax.swing.JLabel item_35;
    private javax.swing.JLabel item_36;
    private javax.swing.JLabel item_37;
    private javax.swing.JLabel item_38;
    private javax.swing.JLabel item_39;
    private javax.swing.JLabel item_4;
    private javax.swing.JLabel item_40;
    private javax.swing.JLabel item_41;
    private javax.swing.JLabel item_42;
    private javax.swing.JLabel item_5;
    private javax.swing.JLabel item_6;
    private javax.swing.JLabel item_7;
    private javax.swing.JLabel item_8;
    private javax.swing.JLabel item_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel rate;
    private javax.swing.JLabel subtotal;
    // End of variables declaration//GEN-END:variables
}
